### ISSUE TITLE
syntax error , line 424

### ISSUE THREAD

**Issue by yonglinteh** [devinsays/woocommerce-coupon-restrictions#6] opened 2017-12-01 05:51 UTC
Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /home4/waealy0acpcs/public_html/wp-content/plugins/woocommerce-coupon-restrictions-master/woocommerce-coupon-restrictions.php on line 424

**Comment by jatiyanon** [comment] 2017-12-06 17:28
Duplicate of #5

**Comment by devinsays** [comment] 2017-12-18 16:52
Thanks for the bug report (for some reason email notifications weren't coming through to me). Try it now, there have been some changes in the last week.

**Closed by devinsays** 2017-12-18 16:52 UTC
